RubyOnRails/SMX/smx/config/routes.rb
Rails.application.routes.draw do
  get 'contact_requests/index'
  get 'contact_requests/request'
  #USER ROUTRES
  get "/smx", to:"user#index", as:"front"
  get "/smx/new", to:"user#new", as:"users"
  get "/smx/profile/:id", to:"user#profile", as:"profile"
  post "/smx/new", to:"user#create"
  delete "/smx/profile/:id", to:"user#destroy"
  
  #HOMEPAGE ROUTES
  get "/homepage", to:"homepage#index", as:"homepage"
  get "/homepage/real", to:"homepage#real", as:"real"
  get "/homepag/sim", to:"homepage#sim", as:"sim"
  get "/homepage/realgame", to:"homepage#realgame", as:"realgame"
  get "/homepage/simgame/:id", to:"homepage#simgame", as:"simgame"
  get "/homepage/results", to:"homepage#results", as:"results"
  get "/homepage/leaderboard", to:"homepage#leaderboard", as:"leaderboard"
  post "/homepage/simgame", to:"homepage#create", as:"simsgame"
  post "/homepage/simgame/:id", to:"homepage#result", as:"simgames"
  
  #SESSION
  get "/smx/login", to: "session#new", as: "login"
  post "/session", to: "session#create"  
  delete "/logout", to: "session#destroy", as:"logout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RubyOnRails/SMX/smx/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RubyOnRails/SMX/smx/app/models/contact_request.rb
class ContactRequest < ApplicationRecord

    belongs_to :user

end

RubyOnRails/SMX/smx/app/models/player.rb
class Player < ApplicationRecord

    has_many :players

end

RubyOnRails/SMX/smx/app/models/simgame.rb
class Simgame < ApplicationRecord
    
    has_many :players
    has_many :users
end

RubyOnRails/SMX/smx/app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password

    validates :username, presence: true
    validates :username, uniqueness: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :team_name, presence: true
    validates :team_name, uniqueness: true


    def exp_score
        self.players.each do |sps|
            index = @p1_sps.index(sps)
            1200.times do
              chance = rand(1000)     
              if @p1_sps[index] > chance
                chance2 = rand(100)
                if @p1_shot_perc[index]>chance2
                  @u1 +=2
                  @p1[index] +=2
                end         
              end
            end 
          end
          return score
    end
end

RubyOnRails/SMX/smx/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?

    def current_user
        if session[:user_id]
            User.find(session[:user_id])
        else
            false 
        end
    end

    def logged_in?
        current_user
    end

    def authorized?
        redirect_to front_path unless logged_in?
    end

end

RubyOnRails/SMX/smx/app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  def index
  end

  def request
    @contactrequest = ContactRequest.new
    @user = User.find(sessions[:user_id])
  end

  def create

  end
end

RubyOnRails/SMX/smx/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  before_action :authorized?

  def leaderboard
    @users = User.all
    @users.max_by{ |user| user.amount}
  end

  def index
    @user = User.find(session[:user_id])
  end

  def real
    @users = User.all
  end
  
  def realgame
  end

  def simgame
    @user1 = User.find(session[:user_id])
    @user2 = User.find(params[:id])
    @simgames = Simgame.new
    @players = Player.all
  end
  
  def sim
    @users = User.all
  end
  
  def create
  end
  
  def result 
    @u1 = 0
    @u2 = 0 
    @p1_sps = []
    @p2_sps = []
    @p1_shot_perc = []
    @p2_shot_perc = [] 
    @p1 = [0,0,0,0,0]
    @p2 = [0,0,0,0,0]
    @user1 = User.find(session[:user_id])
    @user2 = User.find(params[:id])
    players = Player.all
    @p1_1 = Player.find(params["simgame"]["u1p1_id"])
    @p2_1 = Player.find(params["simgame"]["u1p2_id"])
    @p3_1 = Player.find(params["simgame"]["u1p3_id"])
    @p4_1 = Player.find(params["simgame"]["u1p4_id"])
    @p5_1 = Player.find(params["simgame"]["u1p5_id"])
    cpu_player_id = 1+rand(players.size)
    @p1_2 = players[cpu_player_id][:full_name]
    @p2_sps << players[cpu_player_id][:sps]
    @p2_shot_perc << players[cpu_player_id][:shot_perc]
    cpu_player_id = 1+rand(players.size)
    @p2_2 = players[cpu_player_id][:full_name]
    @p2_sps << players[cpu_player_id][:sps]
    @p2_shot_perc << players[cpu_player_id][:shot_perc]
    cpu_player_id = 1+rand(players.size)
    @p3_2 = players[cpu_player_id][:full_name]
    @p2_sps << players[cpu_player_id][:sps]
    @p2_shot_perc << players[cpu_player_id][:shot_perc]
    cpu_player_id = 1+rand(players.size)
    @p4_2 = players[cpu_player_id][:full_name]
    @p2_sps << players[cpu_player_id][:sps]
    @p2_shot_perc << players[cpu_player_id][:shot_perc]
    cpu_player_id = 1+rand(players.size)
    @p5_2 = players[cpu_player_id][:full_name]
    @p2_sps << players[cpu_player_id][:sps]
    @p2_shot_perc << players[cpu_player_id][:shot_perc]
    @p1_sps << @p1_1.sps
    @p1_sps << @p2_1.sps
    @p1_sps << @p3_1.sps
    @p1_sps << @p4_1.sps
    @p1_sps << @p5_1.sps 
    @p1_shot_perc << @p1_1.shot_perc
    @p1_shot_perc << @p2_1.shot_perc
    @p1_shot_perc << @p3_1.shot_perc
    @p1_shot_perc << @p4_1.shot_perc
    @p1_shot_perc << @p5_1.shot_perc

    #@u1 = 0
    #@u2 = 0 
    #@p1_sps = []
    #@p2_sps = []
    #@p1_shot_perc = []
    #@p2_shot_perc = [] 
    #@p1 = [0,0,0,0,0]
    #@p2 = [0,0,0,0,0]

    @p1_sps.each do |sps|
      index = @p1_sps.index(sps)
      1200.times do
        chance = rand(1000)     
        if @p1_sps[index] > chance
          chance2 = rand(100)
          if @p1_shot_perc[index]>chance2
            @u1 +=2
            @p1[index] +=2
          end         
        end
      end 
    end

    #@user1.exp_score

    @p2_sps.each do |sps|
      index = @p2_sps.index(sps)
      1200.times do
        chance = rand(1000)     
        if @p2_sps[index] > chance
          chance2 = rand(100)
          if @p2_shot_perc[index]>chance2
            @u2 +=2
            @p2[index] +=2
          end         
        end
      end 
    end
  end
end

RubyOnRails/SMX/smx/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end  

  def create 
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password_digest])
        session[:user_id] = @user.id 
        redirect_to profile_path(@user)
    else
        flash[:message] = "Incorrect Password or username"
        render :new 
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to front_path
  end
end

RubyOnRails/SMX/smx/app/controllers/user_controller.rb
class UserController < ApplicationController
  
 before_action :authorized?, except: [:new,:create,:login, :index]

  def index
  end

  def update
  end
  
  def login
  end
  
  def new 
    @user = User.new
  end

  def profile
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
      if @user.valid?
        @user.save
        session[:user_id] = @user.id
        redirect_to profile_path(@user)
      else
        flash.now[:message] = @user.errors.full_messages[0]
        render :new
      end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to login_path
  end

  private
  def user_params
    params.require(:user).permit(:full_name,:username,:password,:team_name,:email,:amount)
  end
end

RubyOnRails/SMX/smx/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails/SMX/smx/app/helpers/contact_requests_helper.rb
module ContactRequestsHelper
end

RubyOnRails/SMX/smx/app/helpers/game_helper.rb
module GameHelper
end

RubyOnRails/SMX/smx/app/helpers/homepage_helper.rb
module HomepageHelper
end

RubyOnRails/SMX/smx/app/helpers/session_helper.rb
module SessionHelper
end

RubyOnRails/SMX/smx/app/helpers/user_helper.rb
module UserHelper
end

RubyOnRails/SMX/smx/app/views/contact_requests/index.html.erb
<h1>ContactRequests#index</h1>
<p>Find me in app/views/contact_requests/index.html.erb</p>

RubyOnRails/SMX/smx/app/views/contact_requests/request.html.erb
<h1>ContactRequests#request</h1>

<%=form_for @contactrequest do |f|%>
    <>
<%end%>

<p>Find me in app/views/contact_requests/request.html.erb</p>

RubyOnRails/SMX/smx/app/views/homepage/index.html.erb
<div style="text-align:center;">
    <h2><%=@user.username%></h2>
    <h3>Welcome to SPORTSMATRIX<h3>
    <%=button_to "Sim Games", sim_path, method: :get%>
    <%=button_to "Real Time Games", realgame_path, method: :get%>
    <%=button_to "Leaderboards", leaderboard_path, method: :get%>
    <%=button_to "Profile", homepage_path, method: :get%>
    <%=button_to "Logout", logout_path, method: :delete%>
</div>

RubyOnRails/SMX/smx/app/views/homepage/leaderboard.html.erb
<div style="text-align:center;">
    <h3 style="font-size:35px;">Current Leaderboard</h3>
    <%number = 1%>

    <%sorted = @users.all.sort_by{|user| user.amount}.reverse%>
    <%sorted.each do |user|%>
        <ul>
            <h4><%="#{number}.#{user.username}:#{user.amount}"%></br></h3>
        </ul>
        <%number = number +1%>
    <%end%>

    <%=button_to "Homepage", homepage_path, method: :get%>
</div>

RubyOnRails/SMX/smx/app/views/homepage/real.html.erb
<div style="text-align:center;">
    <h1>Players currently online to play </h1>

    <%@users.each do |user|%>
        <li>
            <%=link_to user.username, "/homepage/game", {:style=>'color:#FFFFFF;', :class => "css_class"}%>
        </li>
    <%end%>

    <%=button_to "Homepage", homepage_path, method: :get%>
    
</div>

RubyOnRails/SMX/smx/app/views/homepage/realgame.html.erb
<div style="text-align:center;">
    This is where a real game will be played

    <%=button_to "Homepage", homepage_path, method: :get%>
</div>

RubyOnRails/SMX/smx/app/views/homepage/result.html.erb
<div style="text-align: center">
    <h5>Results page for </h5>
    </br>
    <h5><%=@user1.username%> vs  <%=@user2.username%></h5>
    </br>
    <h5><%=@p1_1.full_name%>:<%=@p1[0]%>|<%=@p2[0]%>:<%=@p1_2%></br>
    <h5><%=@p2_1.full_name%>:<%=@p1[1]%>|<%=@p2[1]%>:<%=@p2_2%></br>
    <h5><%=@p3_1.full_name%>:<%=@p1[2]%>|<%=@p2[2]%>:<%=@p3_2%></br>
    <h5><%=@p4_1.full_name%>:<%=@p1[3]%>|<%=@p2[3]%>:<%=@p4_2%></br>
    <h5><%=@p5_1.full_name%>:<%=@p1[4]%>|<%=@p2[4]%>:<%=@p5_2%></br>
    </br>
    </br>
    <h1><%=@u1%>:<%=@u2%></h1>

    <%=button_to "Homepage", homepage_path, method: :get%>
    <%=button_to "Sim Games", sim_path, method: :get%>
</div>

RubyOnRails/SMX/smx/app/views/homepage/sim.html.erb
<div style="text-align:center;">
    <h4>Players currently online to play </h4>

    <%@users.each do |user|%>
        <li>
            <%=link_to user.username, "/homepage/simgame/#{user.id}", :style=>'color: #FF8C00;'%>
        </li>
    <%end%>
</div>

RubyOnRails/SMX/smx/app/views/homepage/simgame.html.erb
<div style="text-align: center;">
    <h5 style="font-size:25px">This is where the sim game is played</h5>
    </br>
    <h5 style="font-size:20px"><%=@user1.username%> vs  <%=@user2.username%><h5>
    </br>
    <h5 style="font-size:15px">Pick your team and see how you do <h5>

    <%=form_for @simgames do |f| %>
        <%=f.collection_select(:u1p1_id, @players, :id, :full_name, prompt:"Select Player")%></br>
        <%=f.collection_select(:u1p2_id, @players, :id, :full_name, prompt:"Select Player")%></br>
        <%=f.collection_select(:u1p3_id, @players, :id, :full_name, prompt:"Select Player")%></br>
        <%=f.collection_select(:u1p4_id, @players, :id, :full_name, prompt:"Select Player")%></br>
        <%=f.collection_select(:u1p5_id, @players, :id, :full_name, prompt:"Select Player")%></br>
        <%=f.submit "Start sim"%>
    <%end%>
</div>

RubyOnRails/SMX/smx/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Saira+Stencil+One&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  #<style="background-image: url('/assets/msg.png'); background-repeat: no-repeat;  background-size: cover;"
  #<style="background-image: url('/assets/msg.png; background-repeat: no-repeat;')">
  <body style="background-image: url('/assets/msg2.png'); background-repeat: no-repeat;  background-size: cover;">
    <%= yield %>
  </body>
</html>

RubyOnRails/SMX/smx/app/views/session/new.html.erb
<div style="text-align:center;margin-top: 10%;">
    <h1>SPORTSMATRIX</h1>
    <%if flash[:message]%>
        <h3><%=flash[:message]%></h3>
    <%end%>

    <%=form_tag "/session" do %>
        <%=text_field_tag :username%></br>
        <%=password_field_tag :password_digest%></br>
        <%=submit_tag "log in"%>
    <%end%>
</div>

RubyOnRails/SMX/smx/app/views/user/index.html.erb
<div style="text-align:center; margin-top: 10%;">
    <h1>SPORTSMATRIX</h1>

    <%=button_to "click to login", login_path , method: :get%>
    <%=button_to "click to create account", users_path, method: :get%>

</div>

RubyOnRails/SMX/smx/app/views/user/new.html.erb
<div style="text-align:center;padding-top:10px;">
     <h2>SPORTSMATRIX</h2>

          <%if flash[:message]%>
               <h3><%=flash[:message]%></h3>
          <%end%>

     <%=form_for @user do |f|%>
          <h5>Full Name<%=f.text_field :full_name%></h5> 
          <h5>Team Name<%=f.text_field :team_name%></h5> 
          <h5>Username<%=f.text_field :username%></h5> 
          <h5>Password<%=f.text_field :password%></h5> 
          <h5>Email<%=f.text_field :email%></h5> 
          <h5>Amount<%=f.number_field :amount%></br></h5> 
          <%=f.submit "submit" %>
     <%end%>
     
</div>

RubyOnRails/SMX/smx/app/views/user/profile.html.erb
<div style="text-align:center;">
    <h2><%= @user.team_name%></h2>
    <h3><%= @user.amount%></h3>
    <h3><%= @user.full_name%></h3>
    <h3><%= @user.username%></h3>
    <h3><%= @user.email%></h3>
    <%=button_to "Delete User", @users, method: :delete%>
    <%=button_to "Logout", logout_path, method: :delete%>
    <%=button_to "Homepage", homepage_path, method: :get%>
</div>